import React, { useState, useEffect } from "react";
import "./SettlementPage.css"; // Import your CSS file
//import html2pdf from "html2pdf.js";

const SettlementPage = ({ loggedInAdmin }) => {
  const [rahulValue, setRahulValue] = useState("");
  const [taranginiiValue, setTaranginiiValue] = useState("");
  const [total, setTotal] = useState(0);
  const [halfTotal, setHalfTotal] = useState(0);
  //const [extraPayment, setExtraPayment] = useState(0);
  const [message, setMessage] = useState("");
  const [paymentOption, setPaymentOption] = useState("");
  const [transactionId, setTransactionId] = useState("");
  const [comment, setComment] = useState("");
  const [paidByAdmin, setPaidByAdmin] = useState("");

  useEffect(() => {
    const rahul = parseFloat(rahulValue) || 0;
    const taranginii = parseFloat(taranginiiValue) || 0;
    const newTotal = rahul + taranginii;
    setTotal(newTotal);
    setHalfTotal(newTotal / 2);
    const newExtraPayment = Math.abs(newTotal / 2 - rahul);
    //setExtraPayment(newExtraPayment);

    if (rahul > taranginii) {
      setMessage(`Taranginii needs to pay Rahul ${newExtraPayment} rupees.`);
    } else if (taranginii > rahul) {
      setMessage(`Rahul needs to pay Taranginii ${newExtraPayment} rupees.`);
    } else {
      setMessage("No extra payment required.");
    }

    // Automatically populate the "Paid by Admin Name" field based on the selected payment option
    if (paymentOption === "cash") {
      // If the logged-in admin is Rahul Samgir, set the paidByAdmin state to "Rahul Samgir", otherwise set it to "Taranginii"
      setPaidByAdmin(
        loggedInAdmin === "Rahul Samgir" ? "Rahul Samgir" : "Taranginii"
      );
    } else {
      // If the payment option is not cash, default the paidByAdmin state to an empty string
      setPaidByAdmin("");
    }
  }, [rahulValue, taranginiiValue, paymentOption, loggedInAdmin]);

  const handlePaymentOptionChange = (option) => {
    setPaymentOption(option);
    // Reset Report Module, Comment, and Paid by Admin fields when payment option changes
    setTransactionId("");
    setComment("");
    setPaidByAdmin("");
  };

  const handlePrint = () => {
    // Get current date and time in Indian format
    const currentDate = new Date().toLocaleDateString("en-IN");
    const currentTime = new Date().toLocaleTimeString("en-IN", {
      hour: "numeric",
      minute: "numeric",
      hour12: true,
    });

    // Define the content to be included in the PDF
    const content = `
      <center>
      <h1 style="margin-bottom: 20px;">Settlement Page</h1>
      <table style="width: 100%; text-align: left; border-collapse: collapse;">
        <tr style="background-color: grey;">
          <th style="padding: 10px; border-bottom: 1px solid #ddd;">Rahul Investment</th>
          <td style="padding: 10px; border-bottom: 1px solid #ddd;">${rahulValue}</td>
        </tr>
        <tr style="background-color: lightpink;">
          <th style="padding: 10px; border-bottom: 1px solid #ddd;">Taranginii Investment</th>
          <td style="padding: 10px; border-bottom: 1px solid #ddd;">${taranginiiValue}</td>
        </tr>
        <tr style="background-color: grey;">
          <th style="padding: 10px; border-bottom: 1px solid #ddd;">Total</th>
          <td style="padding: 10px; border-bottom: 1px solid #ddd;">${total}</td>
        </tr>
        <tr style="background-color: lightpink;">
          <th style="padding: 10px; border-bottom: 1px solid #ddd;">Half of Total</th>
          <td style="padding: 10px; border-bottom: 1px solid #ddd;">${halfTotal}</td>
        </tr>
        <tr style="background-color: grey;">
          <th style="padding: 10px; border-bottom: 1px solid #ddd;">Message</th>
          <td style="padding: 10px; border-bottom: 1px solid #ddd;">${message}</td>
        </tr>
        <tr style="background-color: lightpink;">
          <th style="padding: 10px; border-bottom: 1px solid #ddd;">Payment Option</th>
          <td style="padding: 10px; border-bottom: 1px solid #ddd;">${paymentOption}</td>
        </tr>
        <tr style="background-color: grey;">
          <th style="padding: 10px; border-bottom: 1px solid #ddd;">Report Module</th>
          <td style="padding: 10px; border-bottom: 1px solid #ddd;">${transactionId}</td>
        </tr>
        <tr style="background-color: lightpink;">
          <th style="padding: 10px; border-bottom: 1px solid #ddd;">Comment</th>
          <td style="padding: 10px; border-bottom: 1px solid #ddd;">${comment}</td>
        </tr>
        <tr style="background-color: grey;">
          <th style="padding: 10px;">Paid by Admin</th>
          <td style="padding: 10px;">${paidByAdmin}</td>
        </tr>
      </table>
      <p style="margin-top: 20px; font-size: 14px;">Settlement Page generated on ${currentDate} at ${currentTime}</p>
      </center>
      <p style="margin-top: 20px; text-align: center; font-size: 12px;">PDF Generated by Set By Nature Paradise</p>
    `;

    // Create a HTML element with the content
    const element = document.createElement("div");
    element.innerHTML = content;

    // Generate PDF from the HTML element
    /* html2pdf(element);*/
  };

  const handleGooglePay = () => {
    // Handle redirection to Google Pay
    window.location.href = "https://pay.google.com";
  };

  const handlePhonePe = () => {
    // Handle redirection to PhonePe
    window.location.href = "https://www.phonepe.com";
  };

  return (
    <div className="container">
      <div className="heading">
        <h1>Settlement Page</h1>
      </div>
      <div className="input-container">
        <label htmlFor="rahul">Rahul Investment:</label>
        <input
          type="number"
          id="rahul"
          value={rahulValue}
          onChange={(e) => setRahulValue(e.target.value)}
          placeholder="Enter Rahul's value"
        />
      </div>
      <div className="input-container">
        <label htmlFor="taranginii">Taranginii Investment:</label>
        <input
          type="number"
          id="taranginii"
          value={taranginiiValue}
          onChange={(e) => setTaranginiiValue(e.target.value)}
          placeholder="Enter Taranginii's value"
        />
      </div>
      <div className="input-container">
        <label htmlFor="total">Total:</label>
        <input
          type="number"
          id="total"
          value={total}
          readOnly
          placeholder="Total"
        />
      </div>
      <div className="result-container">
        <p>Half of Total: {halfTotal}</p>
        <p>{message}</p>
      </div>

      <div className="payment-buttons-container">
        <button onClick={handleGooglePay}>Pay with Google Pay</button>
        <button onClick={handlePhonePe}>Pay with PhonePe</button>
      </div>
      <br></br>
      <div className="payment-option-container">
        <button onClick={() => handlePaymentOptionChange("online")}>
          Online
        </button>
        <button onClick={() => handlePaymentOptionChange("cash")}>Cash</button>
      </div>
      <br />
      <div className="payment-container">
        {paymentOption === "online" && (
          <>
            <div className="input-container">
              <label htmlFor="transactionId">Report Module:</label>
              <input
                type="text"
                id="transactionId"
                value={transactionId}
                onChange={(e) => setTransactionId(e.target.value)}
                placeholder="Enter Report Module"
              />
            </div>
            <div className="input-container">
              <label htmlFor="comment">Comment:</label>
              <textarea
                id="comment"
                value={comment}
                onChange={(e) => setComment(e.target.value)}
                placeholder="Enter Comment"
              />
            </div>
          </>
        )}
        {paymentOption === "cash" && (
          <div className="input-container">
            <label htmlFor="paidByAdmin">Paid by Admin Name:</label>
            <input
              type="text"
              id="paidByAdmin"
              value={paidByAdmin}
              onChange={(e) => setPaidByAdmin(e.target.value)}
              placeholder="Enter Admin Name"
              readOnly={loggedInAdmin === "Rahul Samgir"} // Prevent editing for other admins
            />
          </div>
        )}
      </div>

      <div className="download-pdf-container">
        <button onClick={handlePrint}>Download PDF</button>
      </div>
    </div>
  );
};

export default SettlementPage;
